apiVersion: v1
kind: ConfigMap
metadata:
  name: spinnaker-demo-config
  namespace: "${parameters.namespace ?: 'spinnaker'}"
data:
  NEW_FEATURE: "true"

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spinnaker-demo
  namespace: "${parameters.namespace ?: 'spinnaker'}"
  labels:
    source: demo4
    stack: frontend
    app: spinnaker
spec:
  replicas: 4
  selector:
    matchLabels:
      source: demo
      app: spinnaker
  template:
    metadata:
      labels:
        source: demo
        app: spinnaker
    spec:
      containers:
      - name: primary
        image: index.docker.io/lwander/spin-kub-v2-demo
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /
            port: 8000
        envFrom:
        - configMapRef:
            name: spinnaker-demo-config

---

kind: Service
apiVersion: v1
metadata:
  name: spinnaker-demo
  namespace: "${parameters.namespace ?: 'spinnaker'}"
spec:
  selector:
    source: demo
    app: spinnaker
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
