apiVersion: v1
kind: Pod
metadata:
  labels:
    app: tomcat8
  name: tomcat8
spec:
  containers:
    - image: 'tomcat:8'
      imagePullPolicy: Always
      name: tomcat8
  nodeSelector:
    workerGroup: spinnaker
